pipeline:
  name: ecomm
  identifier: ecomm
  projectIdentifier: FM_Sandbox
  orgIdentifier: SE_Sandbox
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: fmaz_github
        repoName: shopizerdemo
        build: <+input>
  stages:
    - stage:
        name: BuildEcomm
        identifier: BuildEcomm
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: fmk8s
              namespace: buildfactory
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: BuildEcomm
                  identifier: BuildEcomm
                  spec:
                    connectorRef: dockerhubfrancislabs
                    image: maven
                    shell: Sh
                    command: |-
                      mvn clean install
                      cd sm-shop
                      mvn spring-boot:run
                  description: Build Ecomm
